optimize clear log cron and add console to clear log
mageplaza/magento-2-smtp pull request #359
Opened 2022-03-01 20:51 UTC by BeardTech

2022-06-08 07:48 UTC, alinalexandru requested changes

2022-06-08 07:48 UTC, alinalexandru commented on Console/ClearLog.php
> + * @package Mageplaza\DeleteOrders\Console
Wrong package name.

2022-06-08 07:48 UTC, alinalexandru commented on Console/ClearLog.php
> +    protected $_helperData;
Using underscore for protected variables is deprecated.

2022-06-08 07:48 UTC, alinalexandru commented on Helper/ClearLog.php
> +        if (!$this->helper->isEnabled()) {
This check should be done in command console and in cron.
This helper should do the delete. On good example is that the console command could have a parameter that will overwrite the settings from database.
For example, the delete cron is disabled, but you should be capable to clean the table, if you want.

2022-12-02 05:08 UTC, KhietNguyen83 commented
Thanks for your contribution.
We have updated your issue.
Thank you very much!

2022-12-02 05:08 UTC, closed without merging